[package]
name = "sunshine-client-utils"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
async-trait = "0.1.36"
parity-scale-codec = "1.3.4"
substrate-subxt = "0.11.0"
sunshine-codec = { path = "../codec" }
sunshine-crypto = { path = "../crypto" }
sunshine-pallet-utils = { path = "../pallet" }
