[package]
name = "sunshine-ffi-utils"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
allo-isolate = "^0.1"
async-std = "^1.6"
log = "^0.4"
once_cell = "^1.4"
futures = "^0.3"