[package]
name = "sunshine-ffi-utils"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
allo-isolate = { version = "0.1.7", features = ["catch-unwind"] }
async-std = "1.6.3"
log = "0.4.11"
once_cell = "1.4.1"
