[workspace]
members = [
    "cli",
    "client",
    "codec",
    "crypto",
    "ffi",
    "keystore",
    "node",
    "pallet",
]

[patch.crates-io]
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt" }
