[package]
name = "sunshine-cli-utils"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-std = "1.6.3"
clap = "3.0.0-beta.1"
rpassword = "5.0.0"
substrate-subxt = "0.12.0"
sunshine-client-utils = { path = "../client" }
thiserror = "1.0.20"
