[package]
name = "sunshine-node-utils"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
sc-basic-authorship = "0.8.0-rc6"
sc-client-api = "2.0.0-rc6"
sc-client-db = { version = "0.8.0-rc6", default-features = false, features = ["with-parity-db"] }
sc-consensus = "0.8.0-rc6"
sc-consensus-aura = "0.8.0-rc6"
sc-finality-grandpa = "0.8.0-rc6"
sc-service = { version = "0.8.0-rc6", default-features = false }
sc-transaction-pool = "2.0.0-rc6"
sp-consensus = "0.8.0-rc6"
sp-consensus-aura = "0.8.0-rc6"
sp-core = "2.0.0-rc6"
sp-finality-grandpa = "2.0.0-rc6"
sp-inherents = "2.0.0-rc6"
