[package]
name = "sunshine-codec"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.3.4", optional = true }
sp-core = { version = "2.0.0-rc5", default-features = false }
sp-std = { version = "2.0.0-rc5", default-features = false }
sp-trie = { version = "2.0.0-rc5", default-features = false }
sunshine-crypto = { path = "../crypto", default-features = false }
thiserror = { version = "1.0.20", optional = true }

[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }

[features]
default = ["std"]

std = [
    "parity-scale-codec",
    "sp-core/std",
    "sp-std/std",
    "sp-trie/std",
    "thiserror",
]
