[package]
name = "sunshine-codec"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
parity-scale-codec = "1.3.4"
hash-db = "0.15.2"
sp-trie = "2.0.0-rc5"
thiserror = "1.0.20"

[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
sp-core = "2.0.0-rc5"
sunshine-crypto = { path = "../crypto" }
