[package]
name = "sunshine-crypto"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.2", features = ["unstable"] }
bip39 = "1.0.0-rc1"
generic-array = "0.14.3"
rand = "0.7.3"
secrecy = "0.7.0"
sp-core = "2.0.0-rc5"
strobe-rs = "0.5.4"
thiserror = "1.0.20"
zeroize = "1.1.0"
